#
# ~/.bashrc
#

# # To use fish as interactive shell
if [[ $- == *i* ]] && which fish &> /dev/null && [ "$1" != "interactive" ]; then
    # drop into fish
    exec fish;
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if command -v starship >/dev/null 2>&1; then
    eval "$(starship init bash)"
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/johann/.sdkman"
[[ -s "~/.sdkman/bin/sdkman-init.sh" ]] && source "~/.sdkman/bin/sdkman-init.sh"
