alias dup="docker-compose.sh up"
alias dow="docker-compose.sh down"
alias publ="sbt compile publishLocal && notify-send Published publ || notify-send Failed publ" 
alias publr="ag -l | entr -s 'sbt compile publishLocal && notify-send Published publr || notify-send Failed publr'" # http://eradman.com/entrproject/
alias dpubl="sbt compile publishLocal docker:publishLocal && notify-send Published dpubl || notify-send Failed dpubl"
alias dpublr="ag -l | entr -s 'sbt compile publishLocal docker:publishLocal && notify-send Published dpublr || notify-send Failed dpublr'" # http://eradman.com/entrproject/
alias cpubl="sbt clean compile publishLocal publishLocal && notify-send Published cpubl || notify-send Failed cpubl"
alias cdpubl="sbt clean compile publishLocal docker:publishLocal && notify-send Published cdpubl || notify-send Failed cdpubl"
alias dw='watch docker ps -a'
alias dl='docker logs -f '
alias dprune="docker system prune -a" # remove all docker containers
alias dls="docker ps -a" # list all docker containers
alias sbtr="ag -l | entr sbt" # http://eradman.com/entrproject/
alias reload="ag -l | entr"
alias ctarget="find -name target | xargs rm -rf"
